# -*- coding: utf-8 -*-
"""major_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NnfTtse2GRRkrbOyoA4ul3RdnEdILdjS

Dataset Understanding
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# For better visuals
sns.set(style="whitegrid")

df = pd.read_csv("Crop_recommendation.csv")
df.head()

df.shape
print("no of row = ",df.shape[0] )
print("no of coloum = ", df.shape[1])

print("Columns in Dataset:")
print(df.columns)

df.info()
df.isnull().sum()

df.describe()

print("Number of unique crops:", df['label'].nunique())
print(df['label'].unique())

"""- The dataset contains 2200 samples and 7 numerical features.
- There are approximately 20+ unique crop categories.
- The dataset appears balanced across crop labels.
- No missing values are present.
- All input features are numeric and suitable for ML/DL models.

Exploratory Data Analysis (EDA)
"""

plt.figure(figsize=(12,6))
sns.countplot(x='label', data=df, order=df['label'].value_counts().index)
plt.xticks(rotation=90)
plt.title("Crop Category Distribution")
plt.show()

"""The dataset appears balanced, with approximately equal samples per crop category.
This ensures that classification models will not be biased toward any particular crop.
"""

df.hist(figsize=(12,10), bins=20)
plt.tight_layout()
plt.show()

"""The features show varied ranges and distributions.
Some features such as rainfall and humidity have wider spreads, indicating strong variability across crop types
"""

plt.figure(figsize=(8,6))
sns.heatmap(df.drop("label", axis=1).corr(), annot=True, cmap="coolwarm")
plt.title("Feature Correlation Heatmap")
plt.show()

"""The heatmap shows moderate correlations among certain features,
but no extremely high multicollinearity is observed.
This indicates that all features can contribute meaningfully to the model.
"""

plt.figure(figsize=(12,8))
for i, col in enumerate(df.columns[:-1], 1):
    plt.subplot(3,3,i)
    sns.boxplot(y=df[col])
    plt.title(col)
plt.tight_layout()
plt.show()

"""No extreme abnormal outliers are observed that would require removal.
The dataset appears well-structured for machine learning applications.

Data Preprocessing
"""

X = df.drop("label", axis=1)
y = df["label"]

print("Feature shape:", X.shape)
print("Target shape:", y.shape)

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y_encoded = le.fit_transform(y)

print("Number of classes:", len(le.classes_))
print("Classes:", le.classes_)

"""The crop labels are encoded into numerical format for classification modeling.
Each unique crop is assigned a distinct integer value
"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y_encoded,
    test_size=0.2,
    stratify=y_encoded,
    random_state=42
)

print("Training set size:", X_train.shape)
print("Test set size:", X_test.shape)

"""The dataset is split into 80% training and 20% testing data using stratified sampling
to preserve class distribution in both sets.
"""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

"""Standardization is applied to normalize feature values.
This ensures that all input variables contribute equally to model training

Machine Learning Models
"""

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

models = {
    "Logistic Regression": LogisticRegression(max_iter=500),
    "Decision Tree": DecisionTreeClassifier(),
    "KNN": KNeighborsClassifier(),
    "SVM": SVC(),
    "Random Forest": RandomForestClassifier()
}

results = []

for name, model in models.items():

    # Train
    model.fit(X_train_scaled, y_train)

    # Predict
    y_pred = model.predict(X_test_scaled)

    # Accuracy
    acc = accuracy_score(y_test, y_pred)

    results.append([name, acc])

    print(f"\n{name}")
    print("-" * 40)
    print("Accuracy:", round(acc, 4))
    print("Classification Report:\n", classification_report(y_test, y_pred))

results_df = pd.DataFrame(results, columns=["Model", "Accuracy"])
results_df.sort_values(by="Accuracy", ascending=False)

from sklearn.model_selection import StratifiedKFold, cross_val_score

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

cv_results = []

for name, model in models.items():
    scores = cross_val_score(model, X_train_scaled, y_train, cv=skf, scoring="accuracy")
    cv_results.append([name, scores.mean()])
    print(f"{name} CV Mean Accuracy: {round(scores.mean(),4)}")

cv_df = pd.DataFrame(cv_results, columns=["Model", "CV Accuracy"])
cv_df.sort_values(by="CV Accuracy", ascending=False)

"""- Tree-based models such as Random Forest generally perform better on structured datasets.
- SVM and Logistic Regression perform well after feature scaling.
- Cross-validation results confirm model stability.
- Random Forest is likely to be the strongest baseline model.

Advanced Machine Learning Models
"""

from sklearn.ensemble import GradientBoostingClassifier, ExtraTreesClassifier
from xgboost import XGBClassifier

advanced_models = {
    "Gradient Boosting": GradientBoostingClassifier(),
    "Extra Trees": ExtraTreesClassifier(),
    "XGBoost": XGBClassifier(
        eval_metric="mlogloss",
        use_label_encoder=False,
        random_state=42
    )
}

advanced_results = []

for name, model in advanced_models.items():

    model.fit(X_train_scaled, y_train)
    y_pred = model.predict(X_test_scaled)

    acc = accuracy_score(y_test, y_pred)
    advanced_results.append([name, acc])

    print(f"\n{name}")
    print("-" * 40)
    print("Accuracy:", round(acc, 4))
    print("Classification Report:\n", classification_report(y_test, y_pred))

advanced_df = pd.DataFrame(advanced_results, columns=["Model", "Accuracy"])
advanced_df.sort_values(by="Accuracy", ascending=False)

final_comparison = pd.concat([results_df, advanced_df])
final_comparison.sort_values(by="Accuracy", ascending=False)

"""- Advanced ensemble models outperform most baseline models.
- XGBoost and Extra Trees show strong performance on structured agricultural data.
- Boosting-based models capture complex feature interactions better than simple classifiers.

Hyperparameter Tuning

In this phase, we optimize the hyperparameters of the best-performing models
to improve their predictive performance. We use RandomizedSearchCV to efficiently
search the parameter space.
"""

from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

rf_params = {
    'n_estimators': [100, 200, 300, 400],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'bootstrap': [True, False]
}

rf_model = RandomForestClassifier(random_state=42)

rf_random = RandomizedSearchCV(
    estimator=rf_model,
    param_distributions=rf_params,
    n_iter=20,
    cv=5,
    verbose=1,
    random_state=42,
    n_jobs=-1
)

rf_random.fit(X_train_scaled, y_train)

print("Best Random Forest Parameters:")
print(rf_random.best_params_)

best_rf = rf_random.best_estimator_

y_pred_rf = best_rf.predict(X_test_scaled)

print("Random Forest Tuned Accuracy:", accuracy_score(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))

xgb_params = {
    'n_estimators': [100, 200, 300],
    'max_depth': [3, 5, 7],
    'learning_rate': [0.01, 0.05, 0.1],
    'subsample': [0.7, 0.8, 1],
    'colsample_bytree': [0.7, 0.8, 1]
}

xgb_model = XGBClassifier(
    eval_metric='mlogloss',
    use_label_encoder=False,
    random_state=42
)

xgb_random = RandomizedSearchCV(
    estimator=xgb_model,
    param_distributions=xgb_params,
    n_iter=20,
    cv=5,
    verbose=1,
    random_state=42,
    n_jobs=-1
)

xgb_random.fit(X_train_scaled, y_train)

print("Best XGBoost Parameters:")
print(xgb_random.best_params_)

best_xgb = xgb_random.best_estimator_

y_pred_xgb = best_xgb.predict(X_test_scaled)

print("XGBoost Tuned Accuracy:", accuracy_score(y_test, y_pred_xgb))
print(classification_report(y_test, y_pred_xgb))

tuning_results = pd.DataFrame({
    "Model": ["Random Forest", "XGBoost"],
    "Accuracy After Tuning": [
        accuracy_score(y_test, y_pred_rf),
        accuracy_score(y_test, y_pred_xgb)
    ]
})

tuning_results

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

y_pred = best_rf.predict(X_test_scaled)

cm = confusion_matrix(y_test, y_pred)

# Recreate and store trained baseline models

trained_models = {}

models = {
    "Logistic Regression": LogisticRegression(max_iter=500),
    "Decision Tree": DecisionTreeClassifier(),
    "KNN": KNeighborsClassifier(),
    "SVM": SVC(),
    "Random Forest (Base)": RandomForestClassifier(),
    "Gradient Boosting": GradientBoostingClassifier(),
    "Extra Trees": ExtraTreesClassifier()
}

for name, model in models.items():
    model.fit(X_train_scaled, y_train)
    trained_models[name] = model

models_final = {
    **trained_models,
    "Random Forest (Tuned)": best_rf,
    "XGBoost": best_xgb,

}

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import pandas as pd

results = []

for name, model in models_final.items():

    y_pred = model.predict(X_test_scaled)

    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred, average='weighted', zero_division=0)
    rec = recall_score(y_test, y_pred, average='weighted', zero_division=0)
    f1 = f1_score(y_test, y_pred, average='weighted', zero_division=0)

    results.append([name, acc, prec, rec, f1])

results_df = pd.DataFrame(results, columns=["Model","Accuracy","Precision","Recall","F1 Score"])

results_df = results_df.sort_values(by="Accuracy", ascending=False)

results_df

import shap
import pandas as pd

# Convert to DataFrame (important)
X_test_scaled_df = pd.DataFrame(X_test_scaled, columns=X.columns)

# Take small sample for speed (IMPORTANT)
X_sample = X_test_scaled_df.sample(200, random_state=42)

# SHAP Explainer
explainer = shap.Explainer(best_xgb, X_sample)

# Compute SHAP values
shap_values = explainer(X_sample)

# FIX for multi-class → take one class
shap.plots.beeswarm(shap_values[..., 0])

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# Predictions using tuned Random Forest
y_pred_rf = best_rf.predict(X_test_scaled)

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred_rf)

# Plot
plt.figure(figsize=(12,10))
sns.heatmap(cm,
            annot=True,
            fmt='d',
            cmap='Blues',
            xticklabels=le.classes_,
            yticklabels=le.classes_)

plt.xlabel("Predicted Label")
plt.ylabel("Actual Label")
plt.title("Confusion Matrix - Random Forest")

plt.show()